# Generated by Django 3.1.7 on 2021-03-23 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20210322_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_shared',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_within_posts', to='post.post'),
        ),
    ]
