<<<<<<< HEAD
# Generated by Django 3.1.7 on 2021-03-24 14:16
=======
# Generated by Django 3.1.7 on 2021-03-24 10:43
>>>>>>> dev

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('post', '0001_initial'),
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='comment_for',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='post.post'),
        ),
    ]
